Repository kubernetes-sigs/zeitgeist, pull requests merged in 2020-10, with the labels that each got.

#11 Migrate to spf13/cobra for CLI
  .golangci.yml
  cmd/root.go
  cmd/validate.go
  go.mod
  go.sum
  main.go
  zeitgeist.go
Labels: approved, cncf-cla: yes, kind/cleanup, kind/design, kind/feature, lgtm, sig/release, size/XL

#12 upstreams: Update to helm v3.3.4 and use k8s.io/release methods for GitHub client and release retrieval
  dependencies/dependencies.go
  dependencies/versions.go
  go.mod
  go.sum
  upstreams/ami.go
  upstreams/github.go
  upstreams/github_test.go
  upstreams/helm.go
  upstreams/upstreams.go
Labels: approved, cncf-cla: yes, kind/cleanup, kind/feature, lgtm, sig/release, size/XXL

#13 upstreams(helm): Update stable Helm repo location
  upstreams/helm.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, sig/release, size/XS

#14 upstreaming buoy to zeitgeist, stage for combining
  buoy/README.md
  buoy/buoy.go
  buoy/commands/check.go
  buoy/commands/commands.go
  buoy/commands/exists.go
  buoy/commands/float.go
  buoy/commands/needs.go
  buoy/pkg/git/git.go
  buoy/pkg/git/git_test.go
  buoy/pkg/git/info.go
  buoy/pkg/git/ruleset.go
  buoy/pkg/git/ruleset_test.go
  buoy/pkg/golang/goimport.go
  buoy/pkg/golang/goimport_test.go
  buoy/pkg/gomod/check.go
  buoy/pkg/gomod/check_test.go
  buoy/pkg/gomod/float.go
  buoy/pkg/gomod/float_test.go
  buoy/pkg/gomod/modules.go
  buoy/pkg/gomod/modules_test.go
  buoy/pkg/gomod/release_meta.go
  buoy/pkg/gomod/release_meta_test.go
  buoy/pkg/gomod/testdata/bad.example
  buoy/pkg/gomod/testdata/gomod.check1
  buoy/pkg/gomod/testdata/gomod.example1
  buoy/pkg/gomod/testdata/gomod.example2
  buoy/pkg/gomod/testdata/gomod.float1
  buoy/pkg/gomod/testdata/gomod.next1
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XXL

#17 Add buoy owners
  OWNERS_ALIASES
  buoy/OWNERS
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, sig/release, size/S
