Repository kubernetes-sigs/zeitgeist, pull requests merged in 2021-12, with the labels that each got.

#52 add dependabot configuration
  .github/dependabot.yml
Labels: kind/feature, cncf-cla: yes, sig/release, size/S, lgtm, approved

#58 OWNERS: Reflect current Release Engineering roster
  OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/M, sig/release, lgtm, kind/cleanup, approved

#51 Add warning for archived GitHub and GitLab repos
  Makefile
  go.mod
  go.sum
  pkg/gitlab/gitlab.go
  pkg/gitlab/gitlab_test.go
  pkg/gitlab/gitlabfakes/fake_client.go
  upstream/github.go
  upstream/gitlab.go
Labels: kind/feature, cncf-cla: yes, sig/release, size/L, lgtm, approved
