Repository kubernetes-sigs/zeitgeist, pull requests merged in 2021-03, with the labels that each got.

#33 dependencies: Do not warn for every non-matched line in a scanned file
  dependencies/dependencies.go
Labels: approved, cncf-cla: yes, kind/regression, lgtm, sig/release, size/XS

#35 Replace a few internal packages w/ sigs.k8s.io/release-utils
  cmd/root.go
  go.mod
  go.sum
  internal/command/command.go
  internal/command/command_test.go
  internal/command/global.go
  internal/command/global_test.go
  internal/git/describe.go
  internal/git/git.go
  internal/git/git_integration_test.go
  internal/git/git_test.go
  internal/github/github.go
  internal/log/hooks.go
  internal/log/log.go
  internal/log/log_test.go
  internal/log/step.go
  internal/util/common.go
  internal/util/common_test.go
  internal/util/env.go
  internal/util/env_test.go
  pkg/gitlab/gitlab.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, sig/release, size/XXL

#24 tests: use testify to assert the tests
  buoy/go.mod
  buoy/pkg/git/git_test.go
  buoy/pkg/git/ruleset_test.go
  buoy/pkg/golang/goimport_test.go
  buoy/pkg/gomod/check_test.go
  buoy/pkg/gomod/float_test.go
  buoy/pkg/gomod/modules_test.go
  buoy/pkg/gomod/release_meta_test.go
  dependencies/dependencies_test.go
  dependencies/versions_test.go
  upstreams/ami_test.go
  upstreams/dummy_test.go
  upstreams/github_test.go
  upstreams/gitlab_test.go
  upstreams/upstreams_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, sig/release, size/L

#36 commands: Init importable package for zeitgeist commands
  cmd/validate.go
  commands/commands.go
  commands/options.go
  commands/validate.go
  main.go
Labels: approved, cncf-cla: yes, kind/cleanup, kind/design, lgtm, sig/release, size/L

#37 go.mod: Update sigs.k8s.io/release-utils to v0.2.0
  go.mod
  go.sum
  internal/github/github.go
  pkg/gitlab/gitlab.go
Labels: approved, area/dependency, cncf-cla: yes, kind/cleanup, lgtm, sig/release, size/S

#38 commands: Default to remote checks and introduce `--local-only` flag
  commands/commands.go
  commands/options.go
  commands/validate.go
Labels: approved, cncf-cla: yes, kind/cleanup, kind/deprecation, lgtm, sig/release, size/M

#39 Don't pluralize package names when possible and improve debugs
  commands/validate.go
  dependency/dependency.go
  dependency/dependency_test.go
  dependency/version.go
  dependency/version_test.go
  main.go
  pkg/gitlab/gitlab.go
  upstream/ami.go
  upstream/ami_test.go
  upstream/dummy.go
  upstream/dummy_test.go
  upstream/github.go
  upstream/github_test.go
  upstream/gitlab.go
  upstream/gitlab_test.go
  upstream/upstream.go
  upstream/upstream_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, sig/release, size/L

#31 support json and yaml format outputs
  .gitignore
  commands/commands.go
  commands/export.go
  dependency/dependency.go
  dependency/dependency_test.go
  dependency/version.go
  go.mod
  go.sum
  testdata/remote-dummy-with-update.yaml
Labels: approved, cncf-cla: yes, kind/api-change, kind/feature, lgtm, sig/release, size/L
