Repository kubernetes-sigs/zeitgeist, pull requests merged in 2021-02, with the labels that each got.

#22 upstreams: add gitlab as upstream option
  README.md
  dependencies/dependencies.go
  go.mod
  go.sum
  internal/tools.go
  pkg/gitlab/gitlab.go
  pkg/gitlab/gitlab_test.go
  pkg/gitlab/gitlabfakes/fake_client.go
  upstreams/gitlab.go
  upstreams/gitlab_test.go
  upstreams/upstreams.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, sig/release, size/XL

#23 dependencies: cycle February 2021
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, sig/release, size/L

#26 validate: fix base path when validating locally
  cmd/validate.go
  dependencies/dependencies.go
  dependencies/dependencies_test.go
  go.sum
Labels: approved, cncf-cla: yes, kind/bug, lgtm, sig/release, size/L

#28 add support to check for commits on branches in git repos
  pkg/gitlab/gitlab.go
  pkg/gitlab/gitlab_test.go
  pkg/gitlab/gitlabfakes/fake_client.go
  upstreams/github.go
  upstreams/github_test.go
  upstreams/gitlab.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, sig/release, size/L
