Repository kubernetes-sigs/zeitgeist, pull requests merged in 2024-04, with the labels that each got.

#896 upgrade to go 1.22 and housekeeping
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/snapshot.yml
  .go-version
  .golangci.yml
  Makefile
  buoy/go.mod
  cloudbuild.yaml
  commands/export.go
  commands/set_version.go
  commands/upgrade.go
  commands/validate.go
  dependency/dependency.go
  go.mod
  internal/tools.go
  remote/dependency/dependency.go
Labels: kind/feature, cncf-cla: yes, sig/release, size/L, lgtm, kind/cleanup, approved

#907 Increase golangci-lint timeout
  .github/workflows/lint.yml
Labels: cncf-cla: yes, kind/flake, sig/release, size/XS, lgtm, approved

#920 container: Make sure semver sorts higher than non-semver
  upstream/container.go
Labels: kind/bug, cncf-cla: yes, ok-to-test, sig/release, size/XS, lgtm, approved

#929 Enable and fix `perfsprint` linter
  .golangci.yml
  commands/commands.go
  commands/export.go
  commands/set_version.go
  pkg/gitlab/gitlab.go
Labels: cncf-cla: yes, sig/release, size/S, lgtm, kind/cleanup, approved

#932 fix sbom name
  .goreleaser.yml
Labels: kind/bug, cncf-cla: yes, sig/release, size/XS, lgtm, approved

#934 differentiate the local from remote in the version
  commands/commands.go
  main.go
  remote/zeitgeist/main.go
Labels: kind/feature, cncf-cla: yes, sig/release, size/S, lgtm, approved

#935 disabling go proxy for now, looks like we cannot build two different binaries, it build only the root one
  .goreleaser.yml
Labels: kind/bug, cncf-cla: yes, sig/release, size/XS, lgtm, approved
